/**
 * songs.js - Repertório Didático para Prática Guiada e Modo Jogo (Synthesia)
 * Contém notas, durações, compassos e letras formatadas para o motor de jogo
 */

const SONGS_COLLECTION = [
    {
        id: 'ode_to_joy',
        title: 'Ode à Alegria',
        composer: 'L. v. Beethoven',
        difficulty: 'Iniciante',
        tempo: 104,
        description: 'Tema clássico da 9ª Sinfonia. Perfeita para praticar os 5 dedos da mão direita.',
        notes: [
            { note: 'E4', lyric: 'O-', duration: 1 },
            { note: 'E4', lyric: 'de', duration: 1 },
            { note: 'F4', lyric: 'à', duration: 1 },
            { note: 'G4', lyric: 'A-', duration: 1 },
            { note: 'G4', lyric: 'le-', duration: 1 },
            { note: 'F4', lyric: 'gri-', duration: 1 },
            { note: 'E4', lyric: 'a,', duration: 1 },
            { note: 'D4', lyric: 'luz', duration: 1 },
            { note: 'C4', lyric: 'do', duration: 1 },
            { note: 'C4', lyric: 'céu', duration: 1 },
            { note: 'D4', lyric: 'e', duration: 1 },
            { note: 'E4', lyric: 'do', duration: 1 },
            { note: 'E4', lyric: 'a-', duration: 1.5 },
            { note: 'D4', lyric: 'mor', duration: 0.5 },
            { note: 'D4', lyric: '!', duration: 2 },

            { note: 'E4', lyric: 'Can-', duration: 1 },
            { note: 'E4', lyric: 'ta-', duration: 1 },
            { note: 'F4', lyric: 're-', duration: 1 },
            { note: 'G4', lyric: 'mos', duration: 1 },
            { note: 'G4', lyric: 'com', duration: 1 },
            { note: 'F4', lyric: 'fe-', duration: 1 },
            { note: 'E4', lyric: 'rvo-', duration: 1 },
            { note: 'D4', lyric: 'so', duration: 1 },
            { note: 'C4', lyric: 'o', duration: 1 },
            { note: 'C4', lyric: 'teu', duration: 1 },
            { note: 'D4', lyric: 'no-', duration: 1 },
            { note: 'E4', lyric: 'me', duration: 1 },
            { note: 'D4', lyric: 'oh', duration: 1.5 },
            { note: 'C4', lyric: 'Se-', duration: 0.5 },
            { note: 'C4', lyric: 'nhor!', duration: 2 }
        ]
    },
    {
        id: 'twinkle',
        title: 'Brilha, Brilha Estrelinha',
        composer: 'Canção Tradicional',
        difficulty: 'Iniciante',
        tempo: 96,
        description: 'Melodia universal com saltos limpos de 5ª (de Dó para Sol).',
        notes: [
            { note: 'C4', lyric: 'Bri-', duration: 1 },
            { note: 'C4', lyric: 'lha,', duration: 1 },
            { note: 'G4', lyric: 'bri-', duration: 1 },
            { note: 'G4', lyric: 'lha,', duration: 1 },
            { note: 'A4', lyric: 'es-', duration: 1 },
            { note: 'A4', lyric: 'tre-', duration: 1 },
            { note: 'G4', lyric: 'linha,', duration: 2 },
            { note: 'F4', lyric: 'lá', duration: 1 },
            { note: 'F4', lyric: 'no', duration: 1 },
            { note: 'E4', lyric: 'céu', duration: 1 },
            { note: 'E4', lyric: 'a', duration: 1 },
            { note: 'D4', lyric: 'bri-', duration: 1 },
            { note: 'D4', lyric: 'lhar', duration: 1 },
            { note: 'C4', lyric: 'sozinha.', duration: 2 },

            { note: 'G4', lyric: 'Bri-', duration: 1 },
            { note: 'G4', lyric: 'lha,', duration: 1 },
            { note: 'F4', lyric: 'bri-', duration: 1 },
            { note: 'F4', lyric: 'lha,', duration: 1 },
            { note: 'E4', lyric: 'sem', duration: 1 },
            { note: 'E4', lyric: 'pa-', duration: 1 },
            { note: 'D4', lyric: 'rar,', duration: 2 },
            { note: 'G4', lyric: 'lá', duration: 1 },
            { note: 'G4', lyric: 'no', duration: 1 },
            { note: 'F4', lyric: 'céu', duration: 1 },
            { note: 'F4', lyric: 'a', duration: 1 },
            { note: 'E4', lyric: 'cla-', duration: 1 },
            { note: 'E4', lyric: 're-', duration: 1 },
            { note: 'D4', lyric: 'ar.', duration: 2 }
        ]
    },
    {
        id: 'parabens',
        title: 'Parabéns pra Você',
        composer: 'Mildred & Patty Hill',
        difficulty: 'Fácil',
        tempo: 104,
        description: 'A música mais tocada do mundo! Ótima para treinar ritmo ternário.',
        notes: [
            { note: 'C4', lyric: 'Pa-ra-', duration: 0.75 },
            { note: 'C4', lyric: 'béns', duration: 0.25 },
            { note: 'D4', lyric: 'pra', duration: 1 },
            { note: 'C4', lyric: 'vo-', duration: 1 },
            { note: 'F4', lyric: 'cê,', duration: 1 },
            { note: 'E4', lyric: '...', duration: 2 },

            { note: 'C4', lyric: 'nes-ta', duration: 0.75 },
            { note: 'C4', lyric: 'da-', duration: 0.25 },
            { note: 'D4', lyric: 'ta', duration: 1 },
            { note: 'C4', lyric: 'que-', duration: 1 },
            { note: 'G4', lyric: 'ri-', duration: 1 },
            { note: 'F4', lyric: 'da,', duration: 2 },

            { note: 'C4', lyric: 'mui-tas', duration: 0.75 },
            { note: 'C4', lyric: 'fe-', duration: 0.25 },
            { note: 'C5', lyric: 'li-ci-', duration: 1 },
            { note: 'A4', lyric: 'da-', duration: 1 },
            { note: 'F4', lyric: 'des,', duration: 1 },
            { note: 'E4', lyric: 'mui-tos', duration: 1 },
            { note: 'D4', lyric: 'a-nos', duration: 1.5 },

            { note: 'A#4', lyric: 'de', duration: 0.75 },
            { note: 'A#4', lyric: 'vi-', duration: 0.25 },
            { note: 'A4', lyric: 'da!', duration: 1 },
            { note: 'F4', lyric: '', duration: 1 },
            { note: 'G4', lyric: '', duration: 1 },
            { note: 'F4', lyric: '', duration: 2 }
        ]
    },
    {
        id: 'asa_branca',
        title: 'Asa Branca',
        composer: 'Luiz Gonzaga & Humberto Teixeira',
        difficulty: 'Fácil',
        tempo: 104,
        description: 'O clássico hino do forró e baião nordestino brasileiro em tom de Dó.',
        notes: [
            { note: 'C4', lyric: 'Quan-do', duration: 0.5 },
            { note: 'D4', lyric: 'o-', duration: 0.5 },
            { note: 'E4', lyric: 'lhei', duration: 1 },
            { note: 'G4', lyric: 'a', duration: 1 },
            { note: 'G4', lyric: 'ter-ra', duration: 1 },
            { note: 'E4', lyric: 'ar-', duration: 1 },
            { note: 'F4', lyric: 'den-', duration: 1 },
            { note: 'F4', lyric: 'do,', duration: 2 },

            { note: 'C4', lyric: 'qua-le', duration: 0.5 },
            { note: 'D4', lyric: 'fo-guei-', duration: 0.5 },
            { note: 'E4', lyric: 'ra', duration: 1 },
            { note: 'G4', lyric: 'de', duration: 1 },
            { note: 'G4', lyric: 'São', duration: 1 },
            { note: 'F4', lyric: 'Jo-', duration: 1 },
            { note: 'E4', lyric: 'ão...', duration: 2 },

            { note: 'C4', lyric: 'Eu', duration: 0.5 },
            { note: 'D4', lyric: 'per-', duration: 0.5 },
            { note: 'E4', lyric: 'gun-', duration: 1 },
            { note: 'G4', lyric: 'tei', duration: 1 },
            { note: 'G4', lyric: 'a', duration: 1 },
            { note: 'F4', lyric: 'Deus', duration: 1 },
            { note: 'E4', lyric: 'do', duration: 1 },
            { note: 'D4', lyric: 'céu,', duration: 2 },

            { note: 'C4', lyric: 'por', duration: 0.5 },
            { note: 'D4', lyric: 'que', duration: 0.5 },
            { note: 'E4', lyric: 'ta-ma-', duration: 1 },
            { note: 'F4', lyric: 'nha', duration: 1 },
            { note: 'D4', lyric: 'ju-di-', duration: 1 },
            { note: 'C4', lyric: 'ação.', duration: 2 }
        ]
    },
    {
        id: 'fur_elise',
        title: 'Für Elise',
        composer: 'L. v. Beethoven',
        difficulty: 'Médio',
        tempo: 120,
        description: 'O famoso tema da Bagatela em Lá Menor. Ótimo treino de semitons e agilidade.',
        notes: [
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'D#5', lyric: '', duration: 0.5 },
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'D#5', lyric: '', duration: 0.5 },
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'B4', lyric: '', duration: 0.5 },
            { note: 'D5', lyric: '', duration: 0.5 },
            { note: 'C5', lyric: '', duration: 0.5 },
            { note: 'A4', lyric: '', duration: 1.5 },

            { note: 'C4', lyric: '', duration: 0.5 },
            { note: 'E4', lyric: '', duration: 0.5 },
            { note: 'A4', lyric: '', duration: 0.5 },
            { note: 'B4', lyric: '', duration: 1.5 },

            { note: 'E4', lyric: '', duration: 0.5 },
            { note: 'G#4', lyric: '', duration: 0.5 },
            { note: 'B4', lyric: '', duration: 0.5 },
            { note: 'C5', lyric: '', duration: 1.5 },

            { note: 'E4', lyric: '', duration: 0.5 },
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'D#5', lyric: '', duration: 0.5 },
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'D#5', lyric: '', duration: 0.5 },
            { note: 'E5', lyric: '', duration: 0.5 },
            { note: 'B4', lyric: '', duration: 0.5 },
            { note: 'D5', lyric: '', duration: 0.5 },
            { note: 'C5', lyric: '', duration: 0.5 },
            { note: 'A4', lyric: '', duration: 2 }
        ]
    },
    {
        id: 'bella_ciao',
        title: 'Bella Ciao',
        composer: 'Canção Popular Italiana',
        difficulty: 'Médio',
        tempo: 116,
        description: 'Tema tradicional enérgico em Lá menor, mundialmente famoso por La Casa de Papel.',
        notes: [
            { note: 'E4', lyric: 'U-na', duration: 0.5 },
            { note: 'A4', lyric: 'mat-', duration: 0.5 },
            { note: 'B4', lyric: 'ti-', duration: 0.5 },
            { note: 'C5', lyric: 'na', duration: 0.5 },
            { note: 'A4', lyric: '...', duration: 1.5 },

            { note: 'E4', lyric: 'mi', duration: 0.5 },
            { note: 'A4', lyric: 'so-', duration: 0.5 },
            { note: 'B4', lyric: 'no', duration: 0.5 },
            { note: 'C5', lyric: 'sve-', duration: 0.5 },
            { note: 'A4', lyric: 'glia-', duration: 0.5 },
            { note: 'A4', lyric: 'to,', duration: 1 },

            { note: 'E4', lyric: 'o', duration: 0.5 },
            { note: 'A4', lyric: 'bel-la', duration: 0.5 },
            { note: 'B4', lyric: 'ciao,', duration: 0.5 },
            { note: 'C5', lyric: 'bel-la', duration: 0.5 },
            { note: 'B4', lyric: 'ciao,', duration: 0.5 },
            { note: 'A4', lyric: 'bel-la', duration: 0.5 },
            { note: 'C5', lyric: 'ciao,', duration: 0.5 },
            { note: 'D5', lyric: 'ciao,', duration: 0.5 },
            { note: 'E5', lyric: 'ciao!', duration: 1.5 },

            { note: 'E5', lyric: 'u-na', duration: 0.5 },
            { note: 'D5', lyric: 'mat-', duration: 0.5 },
            { note: 'E5', lyric: 'ti-', duration: 0.5 },
            { note: 'F5', lyric: 'na,', duration: 1 },
            { note: 'F5', lyric: 'mi', duration: 0.5 },
            { note: 'E5', lyric: 'so-no', duration: 0.5 },
            { note: 'D5', lyric: 'sve-', duration: 0.5 },
            { note: 'F5', lyric: 'glia-', duration: 0.5 },
            { note: 'E5', lyric: 'to,', duration: 1 },

            { note: 'E5', lyric: 'e', duration: 0.5 },
            { note: 'D5', lyric: 'ho', duration: 0.5 },
            { note: 'C5', lyric: 'tro-', duration: 0.5 },
            { note: 'B4', lyric: 'va-', duration: 0.5 },
            { note: 'A4', lyric: 'to', duration: 1 },
            { note: 'B4', lyric: 'l\'in-', duration: 0.5 },
            { note: 'C5', lyric: 'va-', duration: 0.5 },
            { note: 'B4', lyric: 'sor!', duration: 2 }
        ]
    }
];

window.SONGS_COLLECTION = SONGS_COLLECTION;
